apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-static-website
  labels:
    app: apache-static-website
spec:
  replicas: 1  # You can scale this to more replicas if needed
  selector:
    matchLabels:
      app: apache-static-website
  template:
    metadata:
      labels:
        app: apache-static-website
    spec:
      containers:
      - name: apache
        image: premgowda07/static-website-apache:v1  # Replace with your image
        ports:
        - containerPort: 80  # Apache will serve the website on port 80
        volumeMounts:
        - name: static-content
          mountPath: /usr/local/apache2/htdocs/  # Apache's web root
      volumes:
      - name: static-content
        emptyDir: {}  # This will create a temporary volume for static content
